#!/bin/bash

PUBLIC_IP=$(oc-metadata --cached PUBLIC_IP_ADDRESS)

cat <<EOF
Hi Cloud Rider,
Welcome to the PrivateBin image!
PrivateBin is installed in /srv/www/privatebin/.
Access ZeroBin at http://${PUBLIC_IP}/.
Enjoy!
EOF
