#!/bin/bash

PUBLIC_IP=$(oc-metadata --cached PUBLIC_IP_ADDRESS)

cat <<EOF
Hi Cloud Rider,
Welcome to the ZeroBin image!
ZeroBin is installed in /var/www.
Access ZeroBin at http://${PUBLIC_IP}/.
Enjoy!
EOF
